apiVersion: apps/v1
kind: Deployment
metadata:
  name: enclave-runner-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enclave-runner-container
  template:
    metadata:
      labels:
        app: enclave-runner-container
    spec:
      containers:
      - name: enclave-runner-container
        image: enclave-app-image
        imagePullPolicy: Never
        ports:
        - containerPort: 30000
