apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: NodePort
  selector:
    app: enclave_runner_container
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
      nodePort: 50051
